# Generated by Django 5.2.1 on 2025-05-08 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
